spring:
  application:
    name: Finance Control
  datasource:
    url: jdbc:postgresql://localhost:5432/finance-control-database
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update