spring:
  application:
    name: Finance Control
  datasource:
    url: jdbc:postgresql://localhost:5432/finance-control-database
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
security:
  token:
    secret: BRCOMCONTROLFINANCE2025
    issuer: financecontrol
token:
  sonar: sqp_5c4ec2d21766ab854a936480e16461ddd4bd47fc
